### ISSUE TITLE
Issue with --list-boards and --get-board-info

### ISSUE THREAD

**Issue by sberwick** [drichmond/tinker#6]
Some minor errors with options -i and -l with master.

```
sberwick@4930k-ubuntu:~/tinker$ python2.7 tinker -i 16.0 de5net
Traceback (most recent call last):
  File "tinker", line 136, in <module>
    main()
  File "tinker", line 97, in main
    tinker.check_board(version, board)
AttributeError: Tinker instance has no attribute 'check_board'
```

```
sberwick@4930k-ubuntu:~/tinker$ python2.7 tinker -l
Traceback (most recent call last):
  File "tinker", line 136, in <module>
    main()
  File "tinker", line 90, in main
    tinker = Tinker.Tinker()
  File "/home/elsb3/tinker/python/Tinker.py", line 79, in __init__
    self.get_path_skel()
  File "/home/elsb3/tinker/python/Tinker.py", line 85, in get_path_skel
    self.__check_init()
  File "/home/elsb3/tinker/python/Tinker.py", line 165, in __check_init
    self.__check_init_version()
  File "/home/elsb3/tinker/python/Tinker.py", line 156, in __check_init_version
    if(self.__v is None):
AttributeError: Tinker instance has no attribute '_Tinker__v'
```

**Comment by drichmond** [comment]
I'm pleased someone is trying to use this 

If you're still interested can you drop me an email at drichmond@eng.ucsd.edu?
